### PR TITLE
Navigation to next theorem or chapter

### PR DESCRIPTION
**Pull request by tirix**
And link to the other typesettings.
This PR depends on metmath-knife's [PR #65](https://github.com/david-a-wheeler/metamath-knife/pull/65)

### CODE REVIEW

**Comment by benjub** [comment]
Can you also add a link to http://metamath.tirix.org:3030/mpests/toc or some other page in the README.md ?

It may be me, but I find the colors of the text are a bit too faded (pastel) to permit easy reading.

**Comment by tirix** [comment]
I've updated the theme with a darker black. You might have to hit CTRL+Shift+R to view the changes.
I've also put online this version with the "next" navigation and the links to the other typesettings.

**Comment by benjub** [comment]
Thanks Thierry.  There is some overlapping text among the navigation buttons in the upper-right corner.

The colors are better.  It might be me, but I find it easier to read more "plain" colors, like the 16 predefined html colors: black for text, red for variables, blue for classes, magenta for formula metavariables.  This may look old fashioned and less stylish, so I should not be your only feedback obviously.  The change you made makes it more readable already.

**Comment by benjub** [comment]
Another suggestion: could you indent the "Expression" column as in us.metamath.org, that is, the lines corresponding to the hypotheses of a given line are indented respective to that line.

**Pull request merged**
